version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.2
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # Install and build frontend
      - run:
          name: Install frontend
          command: |
            npm run frontend:install
      - run:
          name: Build frontend
          command: |
            npm run frontend:build
      # Install and build backend
      - run:
          name: Install backend
          command: |
            npm run backend:install
      - run:
          name: Build backend
          command: |
            npm run backend:build
  test:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # migrate the database
      - run:
          name: Migrate database
          command: |
            npm i -g db-migrate db-migrate-pg
            npm run db:migrate
      - run:
          name: Test backend
          command: |
            npm run backend:test
  deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  deploy:
    jobs:
      - build
      - test
      - deploy